carhistory/urls.py
from django.conf.urls.defaults import patterns, url
from django.views.generic.simple import direct_to_template
urlpatterns = patterns('carhistory.views',
    url(r'^$', direct_to_template, {'template':'carhistory/home.html'}, name =  'carhistory_home' ),
    url(r'^result/$', 'history' , name =  'carhistory_result' ),
)

carmarket/urls.py
from django.conf.urls.defaults import patterns
from django.views.generic import ListView
from carmarket.models import StockCar

urlpatterns = patterns ('',
	(r'^thumbs/$', ListView.as_view(model=StockCar)),
)

urls.py
from django.conf.urls.defaults import patterns, include, url
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	url(r'^i18n/', include('django.conf.urls.i18n')),
	url(r'^admin/', include(admin.site.urls)),
	url(r'^market/', include('carmarket.urls')),
	url(r'^history/', include('carhistory.urls')),
	url(r'^$', RedirectView.as_view(url='/history/')),
)

import os
if os.environ['SERVER_SOFTWARE'] == 'local':
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
   )

carhistory/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Vin (models.Model):
	number = models.CharField(max_length = 20)
	model = models.CharField(max_length = 50)
	def __unicode__(self):
		return '%s (%s)' % (self.number, self.model)
	
class CarOwnership (models.Model):
	vin = models.ForeignKey(Vin)
	where = models.CharField(max_length = 50, blank = True, null = True)
	purchase_date = models.DateField(blank = True, null = True)
	release_date = models.DateField(blank = True, null = True)
	mileage = models.IntegerField(blank = True, null = True, help_text = u'Est. mileage during ownership')
	age = models.IntegerField(blank = True, null = True)
	def __unicode__(self):
		return '%s purchased on %s' % (self.vin, self.purchase_date)
	def summary(self):
		result = self.purchase_date.strftime('%d/%m/%y')
		result = u'%s %s, %s' % (_('Transfered:'), result, self.where) if self.where else result

		result = u'%s, %s km' % (result, self.mileage) if self.mileage else result
		return result

class OwnershipHistoryEvent(models.Model):
	EVENT_TYPES = (
		('SV', _('Salvage')),
		('RB', _('Rebuilt')),
		('AC', _('Accident')),
		('TT', _('Title Change')),
	)
	date = models.DateField(help_text = u'Date on which history event occurred')
	mileage = models.IntegerField(blank = True, null = True, help_text = u'Mileage read')
	source = models.TextField(blank = True, null = True, help_text = u'Source of this information, with address')
	comments = models.TextField()
	type = models.CharField(max_length=2, choices = EVENT_TYPES, blank = True, null = True)
	ownership = models.ForeignKey(CarOwnership, blank = True, null = True)
	plate = models.CharField(max_length = 20, blank = True, null = True)
	def __unicode__(self):
		return '%s occurred on %s' % (self.ownership, self.date)		
	def date_km(self):
		result = self.date.strftime('%d/%m/%y')
		result = u'%s<br />%s km' % (result, self.mileage) if self.mileage else result
		return result
		

carmarket/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils.translation import ugettext_lazy as _
from picklefield.fields import PickledObjectField
from sorl.thumbnail import ImageField, get_thumbnail

class Dealer(models.Model):
	CITY_CHOICES = (
		('HCM', _('Ho Chi Minh City')),
		('HN', _('Ha Noi')),
	)
	name = models.CharField(max_length = 256)
	description = models.TextField ()
	address = models.TextField()
	city = models.CharField(max_length = 3, choices = CITY_CHOICES, default = 'HCM' )
	def __unicode__(self):
		return self.name

class CarMake (models.Model):
	make = models.CharField (max_length = 50)
	def __unicode__(self):
		return self.make

class CarYear (models.Model):
	year = models.IntegerField()
	def __unicode__(self):
		return unicode(self.year)

class CarModel (models.Model):
	model = models.CharField(max_length = 50)
	make = models.ForeignKey(CarMake)
	def __unicode__(self):
		return '%s %s' % (self.make, self.model)

class CarStyle (models.Model):
	style = models.CharField(max_length = 50)
	model = models.ForeignKey(CarModel)
	year = models.ForeignKey(CarYear)
	options = PickledObjectField(blank = True, null = True)
	def __unicode__(self):
		return '%s %s %s' % (self.model, self.style, self.year)

class StockCar (models.Model):
	style = models.ForeignKey(CarStyle)
	used = models.BooleanField()
	code = models.CharField(max_length = 10)
	dealer = models.ForeignKey(Dealer)
	loaded_options = PickledObjectField(blank = True, null = True)
	description = models.TextField(blank = True, null = True)
	def __unicode__(self):
		return '%s %s, Code: %s, Dealer: %s' % ( ('Used' if self.used else 'New'), self.style, self.code, self.dealer)
	def thumbnail(self):
		if self.stockphoto_set.all():
			return u'<img src="%s" />' % get_thumbnail(self.stockphoto_set.all()[0].photo, '100x100', crop='center', quality=99).url
		else:
			return '(No Photo)'
	thumbnail.short_description = 'Thumb'
	thumbnail.allow_tags = True	
	
class StockPhoto(models.Model):
	photo = ImageField(upload_to = 'stock')
	car = models.ForeignKey(StockCar)
	title = models.CharField(max_length = 50, blank = True, null = True)
	
class StylePhoto(models.Model):
	photo = ImageField(upload_to = 'style')
	model = models.ForeignKey(CarStyle)
	title = models.CharField(max_length = 50, blank = True, null = True)
	
class ModelPhoto(models.Model):
	photo = ImageField(upload_to = 'model')
	model = models.ForeignKey(CarModel)
	title = models.CharField(max_length = 50, blank = True, null = True)

sorl/thumbnail/models.py
from django.db import models
from sorl.thumbnail.conf import settings


class KVStore(models.Model):
    key = models.CharField(max_length=200, primary_key=True,
        db_column=settings.THUMBNAIL_KEY_DBCOLUMN
        )
    value = models.TextField()

storages/models.py
from django.conf import settings


if settings.DEFAULT_FILE_STORAGE.endswith('mosso.CloudFilesStorage'):
    import warnings
    warnings.simplefilter('always', PendingDeprecationWarning)
    warnings.warn("The mosso module will be deprecated in version 1.2 of "
                  "django-storages. The CloudFiles code has been moved into"
                  "django-cumulus at http://github.com/richleland/django-cumulus.",
                  PendingDeprecationWarning)

carhistory/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponseBadRequest, HttpResponse
from django.template import RequestContext
from django.shortcuts import render_to_response
from carhistory.utils import check_plate_or_vin, LicensePlateOrVinInvalid
from django.utils.translation import ugettext_lazy as _
from carhistory.models import Vin, OwnershipHistoryEvent
import traceback

def history(request):
	try:
		sequence = request.GET.get(u'sequence')
		etemp = 'carhistory/error.html'
		if not sequence: 
			return render_to_response(etemp, {'error':_('Input is empty')}, context_instance=RequestContext(request))
		try:
			checked = check_plate_or_vin(sequence.strip())
		except LicensePlateOrVinInvalid:
			return render_to_response(etemp, {'error':_('Plate number or VIN is not in valid format.')}, context_instance=RequestContext(request))
		if '-' in checked: #this is a plate
			events = OwnershipHistoryEvent.objects.filter(plate = checked)
			if events:
				return render_to_response('carhistory/byplate.html', { 'events': events } , context_instance=RequestContext(request))
		else : #this is a VIN
			vin = Vin.objects.filter(number = checked)
			if vin:
				return render_to_response('carhistory/byvin.html', { 'vin': vin[0] } , context_instance=RequestContext(request))
		return render_to_response(etemp, {'error':_('Vin or Plate number not found.')}, context_instance=RequestContext(request))
	except Exception :
		print(traceback.format_exc())

carmarket/views.py
# Create your views here.

carhistory/templates/carhistory/byplate.html
{% extends "site_base.html" %}
{% load i18n %}

{% block content %}
	<div class="ui-grid-b eventhistoryheader ui-bar-c">
		<div class="ui-block-a">{% trans "Date" %}</div>
		<div class="ui-block-b">{% trans "Source" %}</div>
		<div class="ui-block-c">{% trans "Comments" %}</div>
	</div>
	<div class="ui-grid-b eventhistory">
		{% for event in events %}
			<div class="ui-bar">
				<div class="ui-block-a">{{ event.date_km|safe }}</div>
				<div class="ui-block-b">{{ event.source }}</div>
				<div class="ui-block-c {% if event.type == 'SV' %}majorevent{% endif %}">{{ event.comments}}</div>
			</div>
		{% endfor %}
	</div>
{% endblock %}

carhistory/templates/carhistory/byvin.html
{% extends "site_base.html" %}
{% load i18n %}

{% block content %}
	<h3>{{ vin.model }}</h3>
	<div data-role="collapsible-set" class="ownerhistory">
	{% for ownership in vin.carownership_set.all %}
			<div data-role="collapsible" {% if forloop.first %}data-collapsed="false"{% endif %}>
				<h3>{{ ownership.summary }}</h3>
				<div class="ui-grid-b eventhistoryheader ui-bar-c">
					<div class="ui-block-a">{% trans "Date" %}</div>
					<div class="ui-block-b">{% trans "Source" %}</div>
					<div class="ui-block-c">{% trans "Comments" %}</div>
				</div>
				<div class="ui-grid-b eventhistory">
					{% for event in ownership.ownershiphistoryevent_set.all %}
						<div class="ui-bar">
							<div class="ui-block-a">{{ event.date_km|safe }}</div>
							<div class="ui-block-b">{{ event.source }}</div>
							<div class="ui-block-c {% if event.type == 'SV' %}majorevent{% endif %}">{{ event.comments}}</div>
						</div>
					{% endfor %}
				</div>
			</div> 
	{% endfor %}
	</div>
{% endblock %}

carhistory/templates/carhistory/error.html
{% extends "site_base.html" %}
{% load i18n %}

{% block body %}
	<div data-role="page">
		<div data-role="header">
			<h1 class="ui-title">
				<a href="/" class="ui-link">{% trans "Car History" %}</a>
			</h1>
		</div>
		<div data-role="content">
			<h3>{{ error }}</h3>
		</div>
	</div>

{% endblock %}

carhistory/templates/carhistory/home.html
{% extends "site_base.html" %}
{% load i18n %}
{% block intro %}
	<img class="introimage" src="{{ STATIC_URL }}images/intro.jpg" alt="Tra Số Xe Introductory Image"/>
{% endblock %}
{% block content %}
	 <section class="searchhint">
    	<h3>{% trans "Enter Plate or VIN Number" %}</h3>
    	<h4>{% trans "Example" %}:</h4><span class="sampleinput">50Z-8428</span>
    	<h4>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{% trans "or" %}</h4><span class="sampleinput">RL4BE42K996006052</span>
  	</section>
  	<form action="result" method="get" id="vinsearch" data-ajax="false">
  		<fieldset>
	  		<input data-mini="true" type="search" name="sequence" id="vininput" value="" />
	  		<input data-mini="true" type="submit" data-corners="true" data-shadow="true" data-iconshadow="true" data-wrapperels="span" data-icon="null" data-iconpos="null" data-inline="false" data-mini="false" class="ui-btn ui-shadow ui-btn-corner-all ui-fullsize ui-btn-block ui-btn-up-b" aria-disabled="false" value="{% trans 'View Report' %}" data-theme="c"/>
	  	</fieldset>	
  	</form>
{% endblock %}

carmarket/templates/carmarket/stockcar_list.html
{% extends "site_base.html" %}
{% block content %}
{% for car in object_list %}
	{% for thumb in car.stockphoto_set.all %}
		<div class="thumb75">
			{% load thumbnail %}
			{% thumbnail thumb.photo "75x75" crop="center" quality=99 as im %}
		    	<img src="{{ im.url }}">
			{% endthumbnail %}
		</div>
	{% endfor %}
{% endfor %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
  <head>
	<meta http-equiv="content-type" content="text/html; charset=UTF-8" />  	
	<meta name="description" content="{% block description %}Tra số xe, tra số VIN, Xem tiền sử xe.{% endblock %}" />
<meta name="keywords" content="{% block keywords %}Vietnam, VIN, License Plate, Carfax, Car {% endblock %}" />
	<meta name="author" content="Le Dang " />
	<meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0;" name="viewport" />
	<link rel="shortcut icon" href="{{ STATIC_URL }}images/favicon.ico" type="image/x-icon" />
    <title>{% block title %}Tra Số Xe{% endblock %}</title>
    {% block head %}{% endblock %}
	{% block extra_head %}{% endblock %}
  </head>
  <body>
  	{% block body_wrapper %}
		{% block body %}
		{% endblock %}
		{% block extra_body %}
		{% endblock %}
	{% endblock %}
  </body>
</html>

templates/site_base.html
{% extends "base.html" %}
{% load i18n %}

{% block head %}
	<link href="{{ STATIC_URL }}jquerymobile/jquery.mobile.structure-1.1.0.min.css" rel="stylesheet" />
	<link href="{{ STATIC_URL }}jquerymobile/jquery.mobile-1.1.0.min.css" rel="stylesheet" />
	<link href="{{ STATIC_URL }}jquerymobile/themes/milanweek.min.css" rel="stylesheet" />
	<link href="{{ STATIC_URL }}trasoxe.css" rel="stylesheet" />
	
	<script type="text/javascript" src="{{ STATIC_URL }}jquery/jquery-1.7.1.min.js"></script>
	<script type="text/javascript" src="{{ STATIC_URL }}jquerymobile/jquery.mobile-1.1.0.min.js"></script>
	<script type="text/javascript" src="{{ STATIC_URL }}trasoxe.js"></script>
{% endblock %}

{% block body %}
	<div data-role="header">
		<a data-role="button" data-direction="reverse" data-rel="back" href="{% url carhistory_home %}" data-icon="arrow-l" data-iconpos="left">{% trans "Back" %}</a>
		<h1>
			<a href="/" class="ui-link">{% trans "Car History" %}</a>
		</h1>
		<form action="/i18n/setlang/" data-ajax="false" method="post" id="langform" class="ui-btn-right">{% csrf_token %}
			<input name="next" type="hidden" value="{% url carhistory_home %}" /> 
			<select name="language" data-mini="true">
				{% for lang in LANGUAGES %}
					<option value="{{ lang.0 }}" {% ifequal lang.0 request.LANGUAGE_CODE %}selected="selected"{% endifequal %}>{{ lang.0 }}</option>
				{% endfor %}
			</select>
		</form>
	</div>
	{% block intro %}
	{% endblock %}
	<div data-role="content">
	{% block content %}
	{% endblock %}
	{% block extra_content %}
	{% endblock %}
	</div>
	<div data-role="footer" class="ui-bar-a" data-position="fixed">		
		<div data-role="navbar" class="ui-navbar">
			<ul>
				<li><a href="#" data-icon="search" class="ui-btn-active">{% trans "VIN" %}</a></li>
				<li><a href="#" data-icon="grid">{% trans "Market" %}</a></li>
				<li><a href="#" data-icon="gear">{% trans "Parts" %}</a></li>
			</ul>
		</div><!-- /navbar -->
	</div><!-- /footer -->
{% endblock %}